const parallel = process.env.parallel;
export const config_5 = {
    logo : "https://cdn.igp.com/assets/images/igp-ograph-20211227.png",
    url_prefix : "igp=",
    theme: "#C3404E",
    site_sf: "IGP.com",
    support_email: "support@igp.com",
    support_mobile: "+91-(22) 4343-3333",
    another_support_mobile: "+91-(22) 3965-0300",
    google_site_code : "HmDF1RZFLzvu7X4pe1W0uGObpHiP_qcPubN1pKMN2NI",
    facebook: "https://www.facebook.com/MyIGP",
    twitter: "https://twitter.com/IGPcom",
    linkedin: "https://www.linkedin.com/company/9402791/",
    instagram: "https://www.instagram.com/igpcom/",
    pinterest: "",
    youtube: "https://www.youtube.com/channel/UCctmXlUZP2SoIy4WfZJvf1w",
    allowAMP: true,
    gtmId: "GTM-K992H8",
    site_name : "IGP.com",
    breadcrumb_home_link_text : 'Gifts',
    title_text : "IGP.com",
    about_title_text:"IGP.com: About Us, Who we are - Corporate Information",
    about_meta_description:"IGP.com - About IGP Indian Gifts Portal - Online gifts, flowers & cake delivery from a great selection at India's No.1 Online Gift Shop.",
    about_meta_keywords:"Corporate information, About Us, Who we are, IGP",
    login_title_text:"Log in to IGP | Log In or Sign Up - IGP.com",
    login_meta_description:"Log on to IGP to start gifting and adding Flowers, Cakes, Personalized gifts to your Shopping Cart. Connect with your friends, family and people you know.",
    orderhistory_title_text:"Track Your Order History: Log in & Track Your Gifts Order History - IGP.com",
    orderhistory_meta_description:"Log in & Track Your Order History on IGP.com Now!. Tracking your gifts order with us is Super Easy.",
    orderhistory_meta_keywords:"track your order history, log in & track your order history, track your gift order, gift order status, order shipment history, track order history, IGP order history, order history, IGP track order, IGP order tracking",
    press_releases_title_text:"IGP.com in The News: Press Releases, Media Coverages, Indian Gifts News",
    press_releases_meta_description:"IGP.com is in the news. Checkout Indian Gifts Portal media coverages, press releases, news release, media release, press statement, video release & more.",
    press_releases_meta_keywords:"press releases, IGP in The News, Indian gifts news, news release, media coverage, media release, press statement, video release",
    faq_title_text:"IGP.com: Frequently Asked Questions(FAQ)",
    faq_meta_description:"IGP.com - Frequently Asked Questions(FAQ) - Online gifts, flowers & cake delivery from a great selection at India's No.1 Online Gift Shop.",
    contact_title_text:"IGP.com: Contact Us - IGP.com's Complaint Solution",
    contact_meta_description:"IGP.com - Contact Us - IGP's Complaint Solution from Indian Gifts Portal. Online gifts, flowers & cake delivery from a great selection at India's No.1 Online Gift Shop.",
    searchOrder_title_text:"IGP Track Order: Track Your Gifts Order Status on IGP.com(Indian Gifts Portal)",
    searchOrder_meta_description:"Track Shipment Status or Track your order status on IGP.com. Tracking your online gifts order with us is super easy. Delivering gifts to India since 2000. Enter a valid order number and email id and get the shipment status right away!",
    searchOrder_meta_keywords:"search order, track shipment status, track order status, track your gift order, gift order status, track your order, IGP order status, order history, search your order status, IGP track order, IGP order tracking, details",
    twitter_image : "igp_hb.jpg?v=2",
    facebook_image : "igp_hb.jpg?v=2",
    twitter_site:"@IGPcom",
    twitter_creator:"@IGPcom",
    news_intro: "Indian Gifts Portal is a site which has always been  in the news. Read more about the extensive media coverage of this e-gifting marketplace.",
    google_maps_api: "AIzaSyBCTJxTGv4o7k7XlVwS1hXoj2X8nudDPbc",
    pdpBannerImageForDesktop : "assurance_d_20180601.jpg?v=2",
    pdpBannerImageForMobile : "assurance_m_20180601.jpg?v=2",
    igp_wallet_title_text: 'Your wallet',
    igp_wallet_name: 'IGP Cash',
    cdn : {
        assetsBaseURL:'https://cdn.igp.com/',
    //    assetsURL: 'https://cdn.igp.com/raw/upload/assets/',
         assetsURL: parallel == 'true' ? process.env.SITE_URL + '/' : 'https://cdn.igp.com/raw/upload/assets/',
        bannersURL: 'https://cdn.igp.com/f_auto,q_auto,t_pnoptprodlp/banners/',
        bannersOLDURL: 'https://cdn.igp.com/f_auto,q_auto/banners/',
       // inPageBannersURLD: 'https://cdn.igp.com/f_auto,q_auto,t_inpbannerd/banners/',
       // inPageBannersURLM: 'https://cdn.igp.com/f_auto,q_auto,t_inpbannerm/banners/',
        inPageBannersURLD: 'https://cdn.igp.com/f_auto,q_auto/banners/',
        inPageBannersURLM: 'https://cdn.igp.com/f_auto,q_auto/banners/',
        bannersURLTMres: 'https://cdn.igp.com/f_auto,q_auto,t_mres/banners/',
        cardsURL: 'https://cdn.igp.com/f_auto,q_auto/cards/',
        cardsURLTMres: 'https://cdn.igp.com/f_auto,q_auto,t_mres/cards/',
        productsURL: 'https://cdn.igp.com/',
        productsURLTransformationF: 'f_auto,q_auto,t_prodf/',
        productsURLTransformationL: 'f_auto,q_auto,t_prodl/',
        productsURLTransformationM: 'f_auto,q_auto,t_prodm/',
        productsURLTransformationMEco: 'f_auto,q_auto,t_prodm/', //f_auto,q_auto:eco,t_prodm/
        productsURLTransformationTH: 'f_auto,q_auto,t_prodth/',
        productsURLTransformationFNew: 'f_auto,q_auto,t_pnoptprodlp/',
        productsURLTransformationLNew: 'f_auto,q_auto,t_pnoptprodlp/',
        productsURLTransformationMNew: 'f_auto,q_auto,t_pnoptprodlp/',
        productsURLTransformationMEcoNew: 'f_auto,q_auto,t_pnoptprodlp/', //f_auto,q_auto:eco,t_prodm/
        productsURLTransformationTHNew: 'f_auto,q_auto,t_pnoptprodlp/',
        productsURLBestSellerFlag: 'g_south_east,l_tag',
        blogImageURL:'f_auto,q_auto,t_blogcard/blogs/',
        productsURLFolder1: 'products/',
        persURL: process.env.CDN_PERS_URL,
        videoURLTransformationTH: 'video/upload/q_auto,t_vth/',
        videoURLTransformationL:'video/upload/q_auto,t_prodl/',
        videoURLWatermark:'video/upload/t_vrw',
        videoURLWatermarkReview:'video/upload/q_auto:low',
        videoURL:'video/upload/t_vdl',
        video_bannser_URL:'https://cdn.igp.com/video/upload/f_auto,q_auto/banners/',
        ccsBanner:'f_auto,q_auto,t_ccstp/banners/',
        showcaseNanner : 'f_auto,q_auto,t_cathprect/banners/'
    },
    
    redisKeys:{
        'bestsellers': 'api_bs',
        'feedback': 'api_fb',
        'bestunder999': 'api_bu999',
        'strippage' : 'api_sp',
        'seletionbar' : 'api_selbar',
        'banners' : 'api_ban',
        'cards' : 'api_cards',
        'products' : 'api_pl',
        'products_ab' : 'api_pl_ab',
        'showcase' : 'api_sw',
        'countrycity': 'api_ccs',
        'productdetail': 'api_pd',
        'productfeedback': 'api_pf',
        'homePageRevamp':'api_homeRevamp'
    },
    isBanner : true

};

//'api_bs_#device#_#currency#',

// module.exports = config_5;
